# Generated by Django 6.0.4 on 2026-04-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemeente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vragen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vraag', models.CharField(max_length=255)),
                ('extra_info', models.CharField(blank=True, max_length=255)),
                ('weging', models.IntegerField()),
                ('volgorde', models.IntegerField()),
            ],
        ),
    ]
