# Generated by Django 6.0.4 on 2026-04-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gemeente_vragen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antwoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ja_nee', models.BooleanField()),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('vraag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antwoorden', to='home.vragen')),
            ],
        ),
    ]
