# Generated by Copilot for municipality data fields.

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("home", "0004_valpreventie_vragen"),
	]

	operations = [
		migrations.RenameField(
			model_name="gemeente",
			old_name="contact",
			new_name="telefoonnummer",
		),
		migrations.AlterField(
			model_name="gemeente",
			name="telefoonnummer",
			field=models.CharField(blank=True, default="", max_length=255),
		),
		migrations.AddField(
			model_name="gemeente",
			name="adres",
			field=models.CharField(blank=True, default="", max_length=255),
		),
	]