# Generated by Django 6.0.4 on 2026-05-12 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gemeente_telefoonnummer_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='antwoord',
            name='behaalde_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vragen',
            name='weging_nee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vragen',
            name='weging',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Resultaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessie_key', models.CharField(blank=True, default='', max_length=40)),
                ('gemeente_zoekterm', models.CharField(blank=True, default='', max_length=255)),
                ('totale_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('risico', models.CharField(blank=True, default='', max_length=20)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('gemeente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultaten', to='home.gemeente')),
            ],
        ),
        migrations.AddField(
            model_name='antwoord',
            name='resultaat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antwoorden', to='home.resultaat'),
        ),
    ]
